name: Container image manual build and push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push docker image to Docker Hub
      env:
        REPOSITORY: pierreyveslebrun/semantic-release
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REPOSITORY:$IMAGE_TAG .
        docker push $REPOSITORY:$IMAGE_TAG
